version: '3.8'

services:
  cli:
    build:
      context: .
      dockerfile: docker/cli.Dockerfile
    command: ["/opt/zero-backup/zero-backup", "--test"]

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio_data:/data

  fake-gcs:
    image: fsouza/fake-gcs-server
    container_name: fake-gcs
    command: ["-scheme", "http"]
    ports:
      - "4443:4443"
    volumes:
      - ./storage/fake_gcs_data:/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
    volumes:
      - ./storage/azurite_data:/data

  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    environment:
      FTP_USER: user
      FTP_PASS: pass
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./storage/ftp_data:/home/vsftpd

  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    volumes:
      - ./storage/sftp_data:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001
